export const avatars = {
   gender: ["Man", "Woman"],
   body: ["Pink", "Brown", "OliveBrown"],
   eyes: ["1", "2"],
   eyebrows: ["1", "2"],
   hairstyleMan: [
      "1_Man",
      "2_Man",
      "3_Man",
      "4_Man",
      "5_Man",
      "3_Woman",
      "Unisex",
   ],
   hairstyleWoman: [
      "1_Man",
      "2_Man",
      "3_Man",
      "4_Man",
      "5_Man",
      "1_Woman",
      "2_Woman",
      "3_Woman",
      "4_Woman",
      "Unisex",
   ],
   haircolor: ["Blue", "Brown", "Red", "Yellow"],
   mouth: ["1", "2", "3", "4", "1-Red"],
   moustache: ["1", "2", "3", "4"],
   cheeks: ["1", "2", "3", "Freckles"],
   outfitMan: [
      "1_Man-Blue",
      "1_Man-Bordeaux",
      "1_Man-Grey",
      "2_Man-Blue",
      "2_Man-Grey",
      "3_Man-Black",
      "3_Man-Blue",
      "3_Man-Red",
      "4_Man-Blue",
      "4_Man-Bordeaux",
      "4_Man-Brown",
      "5",
      "6_Security",
      "Unisex-Blue",
      "Unisex-Red",
      "Unisex-Violet",
      "1_Woman-Blue",
      "1_Woman-Bordeaux",
      "1_Woman-Grey",
   ],
   outfitWoman: [
      "1_Man-Blue",
      "1_Man-Bordeaux",
      "1_Man-Grey",
      "2_Man-Blue",
      "2_Man-Grey",
      "3_Man-Black",
      "3_Man-Blue",
      "3_Man-Red",
      "4_Man-Blue",
      "4_Man-Bordeaux",
      "4_Man-Brown",
      "1_Woman-Blue",
      "1_Woman-Bordeaux",
      "1_Woman-Grey",
      "2_Woman-Black",
      "2_Woman-Blue",
      "2_Woman-Bordeaux",
      "3_Woman-Blue",
      "3_Woman-Bordeaux",
      "3_Woman-Violet",
      "4_Woman-Blue",
      "4_Woman-Grey",
      "4_Woman-Pink",
      "5",
      "6_Security",
      "Unisex-Blue",
      "Unisex-Red",
      "Unisex-Violet",
   ],
};